POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS Cocde Rest Client tool is pretty handy for testing API endpoints",
  "important": true
}

##
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "This is another note",
  "important": false
}